-- MySQL Script generated by MySQL Workbench
-- Thu Dec  1 18:04:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `empresa_internet` ;

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_internet` DEFAULT CHARACTER SET utf8 ;
USE `empresa_internet` ;

-- -----------------------------------------------------
-- Table `empresa_internet`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`Cliente` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `provincia` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`PlanInternet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`PlanInternet` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`PlanInternet` (
  `idPlanInternet` INT NULL,
  `velocidad` INT NULL,
  `precio` VARCHAR(45) NULL,
  `descuento` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlanInternet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`Plan_Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`Plan_Cliente` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`Plan_Cliente` (
  `Cliente_dni` INT NOT NULL,
  `PlanInternet_idPlanInternet` INT NOT NULL,
  INDEX `fk_Plan_Cliente_Cliente_idx` (`Cliente_dni` ASC) VISIBLE,
  INDEX `fk_Plan_Cliente_PlanInternet1_idx` (`PlanInternet_idPlanInternet` ASC) VISIBLE,
  CONSTRAINT `fk_Plan_Cliente_Cliente`
    FOREIGN KEY (`Cliente_dni`)
    REFERENCES `empresa_internet`.`Cliente` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plan_Cliente_PlanInternet1`
    FOREIGN KEY (`PlanInternet_idPlanInternet`)
    REFERENCES `empresa_internet`.`PlanInternet` (`idPlanInternet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
