spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url:  jdbc:mysql://localhost:3306/DB_NAME?useSSL=false&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:datos.sql
      mode: always