version: '3.3'
services:
  db:
    platform: linux/arm64/v8
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db
      # So you don't have to use root, but you can if you like
      MYSQL_USER: admin
      # You can use whatever password you like
      MYSQL_PASSWORD: user_db_passuss
      # Password for root access
      MYSQL_ROOT_PASSWORD: user_db_pass
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db-meli-mysql:/var/lib/mysql
# Names our volume
volumes:
  db-meli-mysql:
