USE movies_db

-- MOSTRAR TODOS LOS REGISTROS DE LA TABLA MOVIES
SELECT * 
FROM movies;

-- MOSTRAR EL NOMBRE, APELLIDO Y RATING DE TODOS LOS ACTORES
SELECT first_name, last_name, rating 
FROM actors;

-- MOSTRAR EL TITULO DE TODAS LAS SERIES Y USAR ALIAS PARA QUE TANTO EL NOMBRE
-- DE LA TABLA COMO EL CAMPO ENTEN EN ESPAÑOL
SELECT title AS titulo
FROM series;

-- MOSTRAR EL NOMBRE DE LOS ACTORES CUYO RATING SEA MAYOR A 7.5
SELECT first_name, last_name
FROM actors
WHERE rating > 7.5;

-- MOSTRAR EL TITULO DE LAS PELICULAS Y EL RATING ORDENADAS POR RATING EN 
-- FORMAS ASCENDENTE
SELECT title
FROM movies 
ORDER BY rating ASC;

-- MOSTRAR LOS TITULOS DE LAS PRIMERAS TRES PELICULOAS EN LA BASE DE DATOS
SELECT title
FROM movies
LIMIT 3;

-- MOSTRAR EL TOP 5 DE LAS PELICULAS CON MAYOR RATING
SELECT *
FROM movies
ORDER BY rating DESC
LIMIT 5;

-- LISTAR LOS PRIMEROS 10 ACTORES
SELECT *
FROM actors
LIMIT 10;

-- MOSTRAR EL TITULO Y RATING DE TODAS LAS PELICULAS CUYO TITULO SEA DE 
-- TOY STORY
SELECT title, rating
FROM movies
WHERE title = 'Toy Story';

-- MOSTRAR TODOS LOS ACTORES CUYOS NOMBRES EMPIEZAN CON SAM
SELECT *
FROM actors
WHERE first_name LIKE "Sam%"

-- MOSTRAR EL TITULO DE LAS PELICULAS QUE SALIERON ENTRE 2004 y 2008
SELECT title
FROM movies
WHERE release_date BETWEEN '2004-01-01' AND '2008-12-31';

-- TRAER EL TITULO DE LAS PELICULAS CON EL RATING MAYOR A 3, CON MAS DE 
-- 1 PREMIO Y CON FECHA DE LANZAMIENTO ENTRE EL AÑO 1988 AL 2009.
-- ORDENAR LOS RESULTADOS POR RATING
SELECT title
FROM movies
WHERE rating > 3
AND awards >= 1
AND release_date BETWEEN '1988-01-01' AND '2009-12-31';

