USE movies_db

-- AGREGAR UNA PELICULA A LA TABLA movies
INSERT INTO movies
VALUES (NULL, NULL, NULL, "Pelicula Agregada", 9.9, 3, "2022-01-01", 50, 2);

-- AGREGAR UN GENERO A LA TABLA genres
INSERT INTO genres
VALUES (NULL, "2022-01-01", NULL, "Zzz", 50, 1);

-- ASOCIAR A LA PELICULA DEL PUTNO 1 CON EL GENERO CREADO EN EL PUNTO 2
UPDATE movies
SET genre_id = 15
WHERE id = 22;

-- MODIFICAR LA TABLA actors PARA QUE AL MENOS UN ACTOR TENGA COMO 
-- FAVORITA LA PELICULA AGREGADA EN EL PUNTO 1
UPDATE actors
SET favorite_movie_id = 22
WHERE id = 49;

-- CREAR UNA TABLA TEMPORAL COPIA DE LA TABLA MOVIES
CREATE TEMPORARY TABLE movies_copia
SELECT * FROM movies;

-- ELIMINAR DE ESA TABLA TEMPORAL TODAS LAS PEILCULAS QUE HAYAN
-- GANADO MENOS DE 5 awards
DELETE FROM movies_copia 
WHERE awards < 5;

-- OBTENER LA LISTA DE TODOS LOS GENEROS QUE TENGAN AL MENOS 
-- UNA PELICULA
SELECT DISTINCT genres.*
FROM movies
INNER JOIN genres
ON movies.genre_id = genres.id;

-- OBTENER LA LISTA DE ACTORES CUYA PELICULA FAVORITA HAYA
-- GANADO MAS DE 3 awards
SELECT actors.*
FROM actors
INNER JOIN movies
ON actors.favorite_movie_id = movies.id
WHERE movies.awards > 3;

-- CREAR UN INDICE SOBRE EL NOMBRE EN LA TABLA movies.
ALTER TABLE movies
ADD INDEX title (title ASC) VISIBLE;

-- CHEQUEE QUE EL INDICE FUE CREADO CORRECTAMENTE
EXPLAIN
SELECT *
FROM movies
WHERE title = "Titanic";

