spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:student
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  h2:
    console:
      enabled: true